include:
  - template: Terraform.latest.gitlab-ci.yml

variables:
  # If not using GitLab's HTTP backend, remove this line and specify TF_HTTP_* variables
  TF_STATE_NAME: test
  TF_CACHE_KEY: test
  # If your terraform files are in a subdirectory, set TF_ROOT accordingly
  TF_ROOT: test
  # TF_ROOT: ${CI_PROJECT_DIR}
  # TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}
